### ISSUE TITLE
UnboundLocalError: local variable 'binlog_pos' referenced before assignment

### ISSUE THREAD

**Issue by mm-ns** [memsql/ditto#2]
I am running the following command:

python replicate.py wms_prod --host 127.0.0.1 --port 3306 --user xyz --password 'abcd1234' but I get the following:

`Traceback (most recent call last):
  File "replicate.py", line 20, in <module>
    stream, memsql_conn = wrap_execution(connect_to_databases, [args])
  File "/opt/ditto-master/scripts/replication_globs.py", line 43, in wrap_execution
    return function(*args)
  File "/opt/ditto-master/scripts/replication_globs.py", line 62, in connect_to_databases
    memsql_conn = connect_to_memsql(args, stream)
  File "/opt/ditto-master/scripts/replication_utils.py", line 198, in connect_to_memsql
    if binlog_pos is None:
UnboundLocalError: local variable 'binlog_pos' referenced before assignment`

Any idea of what's the problem?

**Comment by carlsverre** [comment]
Looks like mysqldump didn't output a MASTER_LOG_POS.  The error you hit points you at the relevant code where we are looking for that variable in the output.
